### PR TITLE
Remove dependency on bash

### PR DESCRIPTION
**Pull request by SethDavenport**
The old shell script is now written in JavaScript.

Connected to rangle/rangle-starter#28.

### CODE REVIEW

**Comment by SethDavenport** [comment]
@bennett000

**Comment by SethDavenport** [comment]
Connected to rangle/rangle-starter#28

**Comment by JaKXz** [comment]
@SethDavenport I updated the PR description for you with the connecting keywords so that the connection is made on Waffle :)

Also, [commander](https://www.npmjs.com/package/commander) would make this easier to write... should've pointed it out earlier, my bad!

**Comment by bennett000** [comment]
I love portability. :shipit:

**Comment by SethDavenport** [comment]
Thanks guys.

**Pull request merged**
